version: '3'

services:
  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'

    environment:
      - NODE_ENV=development
    ports:
      - '${NODE_PORT}:${NODE_PORT}'

  client:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    volumes:
      - './services/app:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:${NODE_PORT}
    depends_on:
      - node
    ports:
      - '${PORT}:${PORT}'

volumes:
  database: